init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
